node:
  min_distance_accept: 2.0
  min_number: 5
  dbscan_min_sample: 20
  dbscan_eps: 1.5 # usmma_sim: 1.5 plane: 1.5

edge:
  max_distance: 100000000000.0
  min_number: 10

# best performance on the plane dataset
matching:
  use_type: False
  use_shape: True
  re_match: True
  mu: 8.0
  min_eigenvector_accept: 0.00 # usmma_sim: 0.0 plane: 0.0
  min_number: 5
  min_inliers: 4
  mu_shape: 2.0 # usmma_sim: 2.0 plane: 2.0
  object_rej_threshold: 5.0

