# loop_closure:
use_ringkey: False      # If you want to use ringkey for loop closure, not yet implemented
use_context: False
context_diff: 200        # maximum context difference to accept a loop closure
max_dist: 40.0          # maximum distance to accept a potential loop closure plane: usmma: 40 plane: 20
max_angle: 180.0        # maximum angular distance to accept a potential loop closure plane: 90 usmma: 180
min_overlap: 0.85        # minimum overlap to accept a loop closure summa_sim: 0.85 plane: 0.95


cov_scale: 20.0         # scale for expand the loop closure fitness score to loop closure covariance
icp: config/icp.yaml    # ICP parameters
window_size: 3          # window size for loop closure
visualize: False         # if you want to visualize the loop closure

pcm_type: 2             # 0: nothing, 1: pcm, 2: gcm
                        # This parameter only work for DRACO2
min_pcm_value: 5        # minimum number of loop closure to perform pcm
min_num_points: 30      # minimum number of points to perform loop closure usmma_sim: 30 plane:100
pcm_queue_size: 5       # size of the queue for pcm/gcm
num_scan_one_time: 20   # maximum number of scans to send to neighbor each time

inter_factor_type: 3    # -1: no graph optimization, test the cloud registration only
                        #  0: prior, 1: between, 2: whole graph, 3: DRACO
                        # This parameter only work for DRACO2
noise_model_type: 2     # 0: fixed default, 1: icp fitness score, 2: robust noise model

exchange_inter_robot_factor: False # if you want to exchange inter robot factors, False for whole graph
use_best_loop: False

